sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - $HOME/.yarn-cache
install:
  - npm install -g yarn
  - yarn install
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
