get:
  summary: Get personal settings
  description: Fetch all stored settings for the user.
  tags:
    - Settings
  responses:
    "200":
      description: Settings
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Preference"
    "404":
      description: Not found
post:
  summary: Create personal setting
  tags:
    - Settings
  requestBody:
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/Preference"
    description: Preference to add
    required: true
  responses:
    "200":
      description: Newly added preference object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Preference"
    "400":
      description: Validation failed
