get:
  summary: Get company settings
  description: Fetch all stored settings for the users company.
  tags:
    - Settings
  responses:
    "200":
      description: Setting values
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Preference"
    "404":
      description: Not found
